# Copyright Ignacio.
# Licensed under BSD 3-Clause License, see LICENSE for details.

PROGRAM = test
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))


EXTRA_SRCS :=

#PROGRAM_CFLAGS := -lm -O0

include ${PROGRAM_DIR}/../common/common.mk
